name: CI

on:
  pull_request:
  push:
    # Comment out this section to enable testing of all branches.
    # branches:
    #   - master


jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-latest
        compile_from_elisp:
          - no
          - yes
        emacs_version:
          # XXX Emacs 26.1's make install doesn't install emacs-module.h
          # - 26.1
          - 26.3
          - snapshot

    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v2
    - name: Install CMake
      run: sudo apt install cmake

    - name: Install libvterm
      if: ${{ matrix.os == 'ubuntu-20.04'}}
      run: |
        sudo apt-get install libvterm-dev

    - name: Install other dependencies
      run: sudo apt install libtool-bin

    - name: Install spell-checker (if linting)
      if: ${{matrix.os == 'ubuntu-20.04'}}
      run: sudo apt install hunspell

    - name: Compile vterm
      if: ${{matrix.compile_from_elisp == 'no'}}
      run: |
           mkdir build
           cd build
           cmake ..
           make
           ldd ../vterm-module.so
    - name: Fix Libary not found
      run:  sudo /sbin/ldconfig -v


    - name: Compile vterm from Emacs
      if: ${{matrix.compile_from_elisp == 'yes'}}
      run: emacs -Q --batch -L . -l vterm-module.so -l vterm.el --eval "(require 'vterm)"


    # - name: Build the dynamic module
    #   run: |
    #     cc -I$HOME/.nix-profile/include -shared -fpic strptime-core.c -o strptime-core.so
    # - name: Byte compile
    #   run: |
    #     emacs -Q --batch -L . --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile *.el
    # - name: Run tests
    #   run: |
    #     emacs -Q --batch -L . -l *-tests.el -f ert-run-tests-batch-and-exit


# jobs:
#   build:
#     runs-on: ${{matrix.os}}
#     strategy:
#       fail-fast: true
#       matrix:
#         emacs_version:
#           - snapshot
#         os:
#           - ubuntu-20.04
#         compile_from_elisp:
#           - no
#     steps:
#     - uses: purcell/setup-emacs@master
#       with:
#         version: ${{ matrix.emacs_version }}

#     - uses: actions/checkout@v2

#     - name: Grab makem.sh
#       uses: wei/wget@v1
#       with:
#         args: https://raw.githubusercontent.com/alphapapa/makem.sh/master/makem.sh

#     - name: Initialize sandbox
#       run: |
#         SANDBOX_DIR=$(mktemp -d) || exit 1
#         echo ::set-env name=SANDBOX_DIR::$SANDBOX_DIR
#         bash makem.sh -vv --sandbox=$SANDBOX_DIR --install-deps --install-linters

#     - name: Install CMake
#       run: sudo apt install cmake

#     - name: Install libvterm
#       if: ${{ matrix.os == 'ubuntu-20.04'}}
#       run: |
#         sudo apt-get install libvterm-dev

#     - name: Install other dependencies
#       if: ${{matrix.os == 'ubuntu-16.04'}}
#       run: sudo apt install libtool-bin

#     - name: Install spell-checker (if linting)
#       if: ${{matrix.os == 'ubuntu-20.04'}}
#       run: sudo apt install hunspell

#     - name: Compile vterm
#       if: ${{matrix.compile_from_elisp == 'no'}}
#       run: |
#            mkdir build
#            cd build
#            cmake ..
#            make
#            ldd ../vterm-module.so
#     - name: Fix Libary not found
#       run:  sudo /sbin/ldconfig -v


#     - name: Compile vterm from Emacs
#       if: ${{matrix.compile_from_elisp == 'yes'}}
#       run: bash makem.sh -vv --sandbox=$SANDBOX batch -- -l vterm-module.so -l vterm.el --eval "(require 'vterm)"

#     - name: Require vterm
#       run: bash makem.sh -vv --sandbox=$SANDBOX batch -- -l vterm-module.so -l vterm.el --eval "(require 'vterm)"

#     - name: Lint
#       # We only need to lint once
#       if: ${{ matrix.os == 'ubuntu-20.04' && matrix.emacs_version == 'snapshot'}}
#       continue-on-error: true
#       run: bash makem.sh -vv --sandbox=$SANDBOX_DIR --exclude makem-pre-test-conf.el lint

#     # - name: Test
#     #   if: always()  # Run test even if linting fails.
#     #   run: bash makem.sh -vv --sandbox=$SANDBOX_DIR test

# # Local Variables:
# # eval: (outline-minor-mode)
# # End:
